### ISSUE TITLE
Explain how to save/update related model data

### ISSUE THREAD

**Issue by fleiflei** [tombenner/wp-mvc-doc#1]
Please extend the docs with a little info on how to save related model data (perhaps in "Models>Saving Data"), especially HABTM.

I had to look into the mvc_model code to find out that to save a bunch of related models to the current model you have to set

``` php
$model_data['RelatedModelName']['ids'] = array(
 0 => '1',
 1 => '97',
 2 => '1234'
);
```

in order to have the association set. Maybe I'm lazy but to make things easier for others, this would be a great hint for the docs!

To me the documentation was the reason I decided to use this MVC plugin for WP. 
Thanks a lot for the good work!

**Comment by cyberscribe** [comment]
Version 1.3 makes many changes and improvements. Please try the latest version and re-open an issue if you are still having a problem.
