### ISSUE TITLE
MVC Fatal Errors and too many warnings

### ISSUE THREAD

**Issue by prabhuchelladurai** [tombenner/wp-mvc-doc#2]
[MVC] Fatal Error: Field "city_code" not found for use in a form input.
Thrown on line 5 of /var/www/html/wordpress/wp-content/plugins/world-cities/app/views/admin/cities/add.php 

Warning: mysql_real_escape_string(): Access denied for user 'www-data'@'localhost' (using password: NO) in /var/www/html/wordpress/wp-content/plugins/wp-mvc/core/models/mvc_database.php on line 34

Please find me a solution. 
Thankyou.

**Comment by prabhuchelladurai** [comment]
I created a plugin in the name WorldCities, which is expected to add, view, edit and update, delete records into the table wp_world_cities. When i try to add a city i got the above error. Warnings are lavishly issued by the compiler. Could you please suggest me a solution? By the way, i am in the very early stage of development. Very new. And i have to develop a plugin using WP-MVC in wordpress supported by Blade templating engine for PHP.
Pl advice accordingly. Pl be elaborate.
Thanks.

**Comment by prabhuchelladurai** [comment]
Warning: mysql_real_escape_string(): Access denied for user 'www-data'@'localhost' (using password: NO) in /var/www/html/wordpress/wp-content/plugins/wp-mvc/core/models/mvc_database.php on line 34

For the problem cited above i found solution in the Forum. 
But For the below cited issue, i need a solution.
Thanks.

 [MVC] Fatal Error: Field "city_code" not found for use in a form input.
Thrown on line 5 of /var/www/html/wordpress/wp-content/plugins/world-cities/app/views/admin/cities/add.php

**Comment by prabhuchelladurai** [comment]
Hi Tom,
I am new to development and i have been assigned to learn and create a plugin with WP MVC in wordpress. And also i am instructed to use Blade in PHP. With only the literal meaning of wordpress, i have come as far as possible of creating a plugin using WP MVC. But i dont know how to interrelate models, views and controllers. i trying my best and am still far away from retreiving a record from the table in the view and add a record to the table. 

That was what i have given in the previous issues. I have still a long way to go..
Could you please guide me in the right direction? i desperately need help...

**Comment by cyberscribe** [comment]
Version 1.3 makes many changes and improvements. Please try the latest version and re-open an issue if you are still having a problem.
