### ISSUE TITLE
Note that flushing the rewrite rules after editing routes.php is necessary

### ISSUE THREAD

**Issue by grubersjoe** [tombenner/wp-mvc-doc#4]
When adding or editing routes in app/config/routes.php it is neccessary to flush the WP rewrite rules. Otherwise newly created or changed routes won't take effect. It took me quite a while to figure out why my correctly defined routes won't work.

To avoid frustration of other developers, who might not be aware of the flush_rewrite_rules() function like me, it would be helpful to add a short note in the documentation how to resolve this. The plugin should either be deactivated and activated again or one should call the flush_rewrite_rules() manually.

I took the following approch, while the routing is not finalized yet:

``` php
// in the main plugin file
add_action('init', function () {
    flush_rewrite_rules();
});
```

If you like I'd create a pull request for this issue.

**Comment by cyberscribe** [comment]
While it may be acceptable in a local development environment to call `flush_rewrite_rules` on init, it is _very bad practice_ in a production environment. I have personally seen it lead to intermittent page unavailability due to race conditions on high-traffic sites. This is why we do not call it as part of the wpmvc plugin.

More details: https://codex.wordpress.org/Function_Reference/flush_rewrite_rules

**Comment by grubersjoe** [comment]
This snippet is of course not intended to be used in production.
My main point is to add a notice to the documentation why the routes may not work immediately. Some developers might not know that rewrite rules need to be flushed in WordPress.

**Comment by cyberscribe** [comment]
Indeed, it's been languishing on my to-do list to update documentation for some time. If you'd be at all interested in working on that, I'd be happy to introduce you to Tom, with an eye toward him giving you access to the documentation repo. There are sadly now quite a few "hidden features" as well that have improved the package but haven't made it back to the documentation yet.

**Comment by cyberscribe** [comment]
It is at least in the FAQ on the main plugin page: https://wordpress.org/plugins/wp-mvc/faq/ --but I agree it should be on the documentation site as well.

**Comment by grubersjoe** [comment]
Well I wouldn't work on it long-term, but I certainly could write some additions, where I think useful information lacks.
